modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/luxmiyu/adm2-ae2/issues"
license = "MIT"

[[mods]]
modId = "adm2_ae2"
version = "${version}"
displayName = "Any Dimension Mod 2 - Applied Energistics 2"
authors = "luxmiyu"
description = '''
Adds dimensions for Any Dimension Mod 2 using blocks from Applied Energistics 2.
'''
logoFile = "icon.png"

[[dependencies.adm2-ae2]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adm2-ae2]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

#[[mixins]]
#config = "adm2-ae2.mixins.json"
